### PR TITLE
Fix typo in accept_attachment example

### PR DESCRIPTION
**Pull request by drAlberT**

### CODE REVIEW

**Comment by drewmullen** [comment]
Hi 👋 Thanks for opening up this PR. Whats the context here regarding this being a typo? Either value is valid

**Comment by drAlberT** [comment]
Hi,
 it's a text part of an example .. and the example states this value to be false ;)

**Comment by drAlberT** [comment]
Screenshot from 2023-01-27 00-39-22

should be

Screenshot from 2023-01-27 00-38-54

**Comment by drewmullen** [comment]
LOL great catch, @pablo19sc can you confirm which is accurate. Is it the statement or the code snippet?

**Comment by drAlberT** [comment]
> LOL great catch, @pablo19sc can you confirm which is accurate. Is it the statement or the code snippet?

It correct the statement, because the previous example it's already describing the "true" case ;)

**Comment by pablo19sc** [comment]
Correct @drewmullen, the fix should be in the code snippet, so the PR fix it.

**Review by drewmullen — APPROVED** [review]

**Pull request merged**
