### PR TITLE
Update (Tagging/VPC Interface)

### PR DESCRIPTION
**Pull request by tonynv**
Update to VPC Module
- Tagging
image
- Subnet Creation
- Remove hardcoded values for additional subnets

### CODE REVIEW

**Comment by catcharbind** [comment]
Suggestion for subnet naming: <VPC Name>_<AZ>_<Public/Private>
This will make it clear which subnets belong to which VPCs , which AZ and if they are private/public without too many drill downs during setup of other dependent services.

**Review by catcharbind — CHANGES_REQUESTED** [review]
Adding the following in main.tf with the variable defined in variables.tf will allow us to create the VPC conditionally similar to while calling from deploy directory.

create_vpc                = var.create_vpc

**Comment by tonynv** [comment]
> Suggestion for subnet naming: `<VPC Name>_<AZ>_<Public/Private>`
> This will make it clear which subnets belong to which VPCs , which AZ and if they are private/public without too many drill downs during setup of other dependent services.

My naming do you mean the tag name ?

**Comment by catcharbind** [comment]
Yes the value for Tag key “Name”. 

Thanks,

-Arabinda

**Comment by tonynv** [comment]
> Adding the following in main.tf with the variable defined in variables.tf will allow us to create the VPC conditionally similar to while calling from deploy directory.
> 
> create_vpc = var.create_vpc

Tracking this in https://github.com/aws-ia/terraform-aws-vpc/issues/6

**Comment by tonynv** [comment]
> > Suggestion for subnet naming: `<VPC Name>_<AZ>_<Public/Private>`
> > This will make it clear which subnets belong to which VPCs , which AZ and if they are private/public without too many drill downs during setup of other dependent services.
> 
> By naming do you mean the tag name ?

Tracking this in https://github.com/aws-ia/terraform-aws-vpc/issues/2

**Pull request merged**
